version: "3.5"
services:
  bd4nrgdb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    container_name: bd4nrgdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd4nrg
    volumes:
      - ./mysql-files:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - bd4nrg
  dozzle:
    image: amir20/dozzle
    container_name: bd4nrg-logs
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - bd4nrg
  bd4nrgredis:
    image: "redis:alpine"
    container_name: bd4nrgredis
    command: redis-server --requirepass cU7bUfAKHmvvs4yg
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - bd4nrg
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - bd4nrg  
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - "5601:5601"
    networks:
      - bd4nrg
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: sem_logstash
    # restart: on-failure
    depends_on:
      - elasticsearch
      - bd4nrgdb
    volumes:
      - ./volumes/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./volumes/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./volumes/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./volumes/logstash/config/queries/:/usr/share/logstash/config/queries/
    networks:
      - bd4nrg
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
networks:
  bd4nrg:
    name: bd4nrg
    driver: bridge